name: Docker Build and Push

on:
  workflow_dispatch: # manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        if: github.event_name == 'workflow_dispatch'  # only login if manual push
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build multi-arch image and push to Docker Hub
        if: github.event_name == 'workflow_dispatch'  # only build and push if manual
        env:
          DOCKER_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/library-app
        run: npm run docker:build
