name: Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  test_and_lint:
    name: Test and Lint pipeline
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Node setup
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install --retry 5 --fetch-timeout=60000
        # working-directory: ./library

      - name: Check style
        run: npm run lint
        # working-directory: ./library

      - name: Build
        run: npm run build
        # working-directory: ./library

      - name: Tests && Coverage
        # Single command runs tests and generate the report
        run: npm run test:coverage
        # working-directory: ./library

      - name: Upload coverage report
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: ./coverage/
          retention-days: 30
